databaseType = "MariaDb"
id = "c1dc1307-8cf3-497f-93e5-53a9b047ac44"
name = "projekt"

[environments.development]
displayName = "Development database"
url = "jdbc:mysql://localhost:3306/moja_baza"
user = "root"

[flyway]
callbackLocations = [ "filesystem:callbacks" ]
environment = "development"
locations = [ "filesystem:C:/Users/leons/projekt/db/migration" ]
mixed = false
outOfOrder = false
schemaModelLocation = "schema-model"
validateMigrationNaming = false

[flyway.check]
majorTolerance = 0

[flywayDesktop]
developmentEnvironment = "development"
shadowEnvironment = "shadow"

[redgateCompare]
filterFile = "filter.rgf"

[redgateCompare.mysql.options.ignores]
ignoreNewlinesInTextObjects = "off"
